record_results: true

dataloader_params:
  experiment_name: "bootcamp_data"
  dataset_name: "MIDAS"
  base_path: "/standard/UVA-DSA/MIDAS/Organized/Bootcamp/Suturing/Processed/"
  batch_size: 1
  sample_rate: 30
  ignore_clutch: true
  clutch_pressed_value: 0
  drop_neg1: true
  all_trials: [    
    "S105_T1",
    "S106_T1",
    "S106_T2",
    "S112_T1",
    "S112_T2",
    "S116_T1",
    "S116_T2",
    "S116_T4",
    "S116_T5",
    "S118_T1",
    "S200_T1",
    "S201_T1",
    "S201_T2",
    "S202_T1",
    "S203_T1",
    "S204_T1",
    "S209_T2",
    "S210_T1",
    "S214_T1",
    "S214_T4",
    "S214_T6",
    "S215_T3",
    "S215_T4",
    "S217_T2",
    "S217_T3",
    "S217_T4",
    "S218_T1",
    "S219_T1"
    ]


  cv:
    scheme: "gesture_flat" # "gesture_flat" or "group_k_fold" or "gesture_flat" or "trial_split"
    k: 5
    val_ratio: 0.2
    test_ratio: 0.2
    seed: 42
    shuffle: true
    val_same_as_test: false

  modalities: ["trakstar"]

  selections:
    # console: [
    #   "console_pos0","console_pos1","console_pos2","console_pos3","console_pos4","console_pos5",
    #   "console_rot0","console_rot1","console_rot2","console_rot3","console_rot4","console_rot5",
    #   "console_aux0","console_aux1","console_pedal"
    # ]
    # raven: [
    # "raven_field.pos0","raven_field.pos1","raven_field.pos2","raven_field.pos3","raven_field.pos4","raven_field.pos5",
    # "raven_field.ori0","raven_field.ori1","raven_field.ori2","raven_field.ori3","raven_field.ori4","raven_field.ori5"
    # # "raven_field.ori6","raven_field.ori7","raven_field.ori8","raven_field.ori9","raven_field.ori10","raven_field.ori11",
    # # "raven_field.ori12","raven_field.ori13","raven_field.ori14","raven_field.ori15","raven_field.ori16","raven_field.ori17"
    # ] # left rave: 0, 1 ,2 , right: 3,4,5
    # images: ["resnet"]    # ✅ required placeholder even if no variables to select
    # trakstar: [
    # "trakstar_sensor_0_azimuth","trakstar_sensor_1_azimuth","trakstar_sensor_2_azimuth","trakstar_sensor_3_azimuth",
    # "trakstar_sensor_0_elevation","trakstar_sensor_1_elevation","trakstar_sensor_2_elevation","trakstar_sensor_3_elevation",
    # "trakstar_sensor_0_roll","trakstar_sensor_1_roll","trakstar_sensor_2_roll","trakstar_sensor_3_roll",
    # "trakstar_sensor_0_x","trakstar_sensor_1_x","trakstar_sensor_2_x","trakstar_sensor_3_x",
    # "trakstar_sensor_0_y","trakstar_sensor_1_y","trakstar_sensor_2_y","trakstar_sensor_3_y",
    # "trakstar_sensor_0_z","trakstar_sensor_1_z","trakstar_sensor_2_z","trakstar_sensor_3_z"
    # ]
    trakstar: [ 
          "trakstar_sensor_0_azimuth","trakstar_sensor_1_azimuth","trakstar_sensor_2_azimuth","trakstar_sensor_3_azimuth",
    "trakstar_sensor_0_elevation","trakstar_sensor_1_elevation","trakstar_sensor_2_elevation","trakstar_sensor_3_elevation",
    "trakstar_sensor_0_roll","trakstar_sensor_1_roll","trakstar_sensor_2_roll","trakstar_sensor_3_roll",
    "trakstar_sensor_0_x_transformed","trakstar_sensor_0_y_transformed","trakstar_sensor_0_z_transformed",
      "trakstar_sensor_1_x_transformed","trakstar_sensor_1_y_transformed","trakstar_sensor_1_z_transformed",
      "trakstar_sensor_2_x_transformed","trakstar_sensor_2_y_transformed","trakstar_sensor_2_z_transformed",
       "trakstar_sensor_3_x_transformed","trakstar_sensor_3_y_transformed","trakstar_sensor_3_z_transformed"
    ]
    # sw_left: ["sw_left_x"]
    # sw_right: ["sw_right_x"]
    # hand_keypoints: ["hand_left X","hand_left Y","hand_left Z","hand_left Yaw","hand_left Pitch","hand_left Roll","hand_right X","hand_right Y","hand_right Z","hand_right Yaw","hand_right Pitch","hand_right Roll","hand_left_index_tip_X","hand_left_index_tip_Y","hand_left_index_tip_Z","hand_right_index_tip_X","hand_right_index_tip_Y","hand_right_index_tip_Z","hand_left_thumb_tip_X","hand_left_thumb_tip_Y","hand_left_thumb_tip_Z","hand_right_thumb_tip_X","hand_right_thumb_tip_Y","hand_right_thumb_tip_Z"]


  # observation_window: 10 # 3 seconds at 10 Hz
  observation_window: -1 # clips
  step: 1

  keysteps:
    8: "Make C Loop"
    11: "Orient Needle"
    16: "Pull Needle out of Tissue"
    17: "Pull Suture"
    18: "Push Needle Through Tissue"
    20: "Reach Suture"
    22: "Square Knot and Cinch"
    23: "Target Needle"


learning_params:
  lr: 5.0e-5
  epochs: 90
  weight_decay: 5.0e-4
  patience: 30
  lr_drop: 30
  best_chkpoint: "./checkpoints/job_xxx/val_best_model.pt"

tcn_model_params:
  encoder_params:
    input_size: 14
    kernel_size: 23
    layer_sizes: [64, 96, 128]
    layer_type: "TempConv"
    norm_type: "Channel"
  decoder_params:
    input_size: 128
    kernel_size: 23
    layer_sizes: [96, 64, 64]
    layer_type: "TempConv"
    norm_type: "Channel"
    transposed_conv: true
  input_dim: 64
  num_classes: 8

transformer_params:
  d_model: 64
  nhead: 4
  num_layers: 2
  dropout: 0.5
  batch_first: true
  sample_rate: 48000
  n_mels: 64
  hop_length: 512
  n_fft: 1024
  resnet_dim: 2048
  seq_to_one: true


# optional overrides for build_model_cfg_from_dataloader
model_cfg_overrides:
  d_model: 128
  nhead: 4
  num_layers: 2
  dropout: 0.1
  fusion: "cross_attend"
  modality_dropout_p: 0.1


mstcn_model_params:
  features_dim: 2048
  num_f_maps: 64
  num_layers_PG: 11
  num_layers_R: 10
  num_R: 3
